# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Arbitrum Robinhood
description: Arbitrum Robinhood indexer
field_selection:
  transaction_fields:
    - "hash"
networks:
  - id: 42161 # Arbitrum
    start_block: 339730653
    contracts:
      - name: ERC20
        abi_file_path: ./abis/erc20-abi.json
        handler: ./src/ERC20EventHandlers.ts
        events:
          - event: Transfer
# in realtime but doesn't guarentee ordering between chains
# https://docs.envio.dev/docs/HyperIndex/multichain-indexing#unordered-multichain-mode
unordered_multichain_mode: true
