# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Arbitrum Robinhood
description: Arbitrum Robinhood indexer
contracts:
  - name: Deployer
    abi_file_path: ./abis/deployer-abi.json
    handler: ./src/DeployerEventHandlers.ts
    events:
      - event: Deploy
  - name: ERC20
    abi_file_path: ./abis/erc20-abi.json
    handler: ./src/ERC20EventHandlers.ts
    events:
      - event: Transfer
      - event: Approval
networks:
  - id: 42161 # Arbitrum
    start_block: 100000000
    contracts:
      - name: ERC20 #A reference to the global contract definition
        address: 0x9D02A17dE4E68545d3a58D3a20BbBE0399E05c9c
      - name: ERC20 #A reference to the global contract definition
        address: 0x9D02A17dE4E68545d3a58D3a20BbBE0399E05c9c
# in realtime but doesn't guarentee ordering between chains
# https://docs.envio.dev/docs/HyperIndex/multichain-indexing#unordered-multichain-mode
unordered_multichain_mode: true
