# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Arbitrum Robinhood
description: Arbitrum Robinhood indexer
contracts:
  - name: ERC20
    abi_file_path: ./abis/erc20-abi.json
    handler: ./src/ERC20EventHandlers.ts
    events:
      - event: Transfer
        field_selection:
          transaction_fields:
            - "hash"
networks:
  - id: 42161 # Arbitrum
    start_block: 339730653
    contracts:
      - name: ERC20
        address: 0xaf88d065e77c8cC2239327C5EDb3A432268e5831
unordered_multichain_mode: true
